import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import Poetrygardenlogo from '../images/Poetrygardenhomepage.png';
import Flower1 from '../images/Flower1.jpg'; // Example flower image
import Flower2 from '../images/Flower2.jpg'; // Example flower image
import Flower3 from '../images/Flower3.jpg'; // Example flower image
import '../styles/homepage.css';
function HomePage() {
    const navigate = useNavigate();
    return (_jsxs("div", { children: [_jsxs("div", { style: { textAlign: "center", marginTop: "100px" }, children: [_jsx("img", { src: Poetrygardenlogo, alt: "Logo" }), _jsx("h1", { children: " " }), _jsx("button", { className: "btn btn-primary", onClick: () => navigate("/signin"), children: _jsx("span", { className: "btn-txt", children: "Get started" }) })] }), _jsxs("div", { className: "why-section", children: [_jsx("h2", { children: "Why Use Poetry Garden?" }), _jsx("p", { children: "Plant your words, let them grow. Poetry Garden is a welcoming space to publish your poems and share your voice. Whether you're new to poetry or a lifelong writer, our platform helps your work bloom in a beautiful, supportive setting. Connect, create, and grow together. Join a community of poets who read, respond, and inspire. Here, your words don\u2019t just live \u2014 they thrive. \uD83C\uDF3F" }), _jsxs("div", { className: "flower-gallery", children: [_jsx("img", { src: Flower1, alt: "Flower 1", className: "flower-image" }), _jsx("img", { src: Flower2, alt: "Flower 2", className: "flower-image" }), _jsx("img", { src: Flower3, alt: "Flower 3", className: "flower-image" })] }), _jsxs("div", { className: "user-reviews", children: [_jsx("h2", { children: "User Reviews" }), _jsxs("div", { className: "review", children: [_jsxs("p", { children: [_jsx("strong", { children: "John John:" }), " \"Poetry Garden has been an amazing platform for me to share my poems and connect with other poets. Highly recommend!\""] }), _jsx("div", { className: "stars", children: "\u2605\u2605\u2605\u2605\u2605" })] }), _jsxs("div", { className: "review", children: [_jsxs("p", { children: [_jsx("strong", { children: "Barry Allen:" }), " \"I love the supportive community and the beautiful design of the website. It inspires me to write more!\""] }), _jsx("div", { className: "stars", children: "\u2605\u2605\u2605\u2605\u2606" })] }), _jsxs("div", { className: "review", children: [_jsxs("p", { children: [_jsx("strong", { children: "Jane Wonder:" }), " \"A wonderful place to let your creativity bloom. The flower gallery is such a nice touch!\""] }), _jsx("div", { className: "stars", children: "\u2605\u2605\u2605\u2605\u2605" })] })] })] })] }));
}
export default HomePage;
